.TH CGREEN 1 2011-06-03 "" "Focus Manual"
.SH NAME
cgreen \- green client launcher
.SH SYNOPSIS
.B cgreen
.RB [\| \-e \|]
.I client
[
.I arg
\&...
]
.SH DESCRIPTION
.B cgreen
launches 
.I client
with the given arguments and connects it to the 
.BR sgreen (1)
server listening on the unix socket specified by the environment variable
$CNSLSVR or, by default, the file
.IR /tmp/green .
.SH OPTIONS
.TP
.B \-e
Normally
.B cgreen
will fork the client in another process and exit right a way.
This flag causes
.B cgreen
to wait for the client to finish before exiting. This
is useful, for example, when trying to view pdf files from elinks so elinks
does not remove the pdf files permaturely.
.SH ENVIRONMENT
.TP
.B CNSLSVR
The file name of the unix socket the server to connect to is listening for
connections on.
.SH FILES
.TP
.I /tmp/green
Default unix socket to use for connecting to the server.
.SH BUGS
Report bugs to
.BR \| < ruhler@csail.mit.edu >.
