
all: a b g

a: a.c
	gcc -o $@ -I/pkg/sdl-1.2.14/install/include/SDL $< -L/pkg/sdl-1.2.14/install/lib -lSDL

b: b.c
	gcc -o $@ -I/pkg/sdl-1.2.14/install/include/SDL $< -L/pkg/sdl-1.2.14/install/lib -lSDL

g: g.c
	gcc -o $@ -I/pkg/sdl-1.2.14/install/include/SDL $< -L/pkg/sdl-1.2.14/install/lib -lSDL

