@node Boxer
@chapter Boxer
Boxer is a consoler application where you move a small box around the
screen, leaving a trail of where the box has been. The follow keys are
supported.

@table @kbd
@item h
Move the box to the left.

@item j
Move the box down.

@item k
Move the box up.

@item l
Move the box to the right.

@item q
Quit.
@end table

More specifically, the background is solid black, taking up the full screen
dimensions. The current box position is white. Past box positions
are red. The box starts at position (100, 100), and is of size 10x10 pixels.

If you move the box off the screen, it will wrap around to the other side of
the screen, staying on the same 10x10 grid.
