\input texinfo
@setfilename focus.info
@include version.texi
@settitle Focus @value{VERSION} Manual

@copying
This is the Focus @value{VERSION} Manual.

Copyright @copyright{} 2014 Richard Uhler.
@end copying

@titlepage
@title Focus @value{VERSION}
@page
@insertcopying
@end titlepage

@contents

@ifnottex
@node Top
@top Focus Manual

@end ifnottex

@menu
* Introduction:: Introduction to the focus system.
* Boxer:: A Box Game
@end menu

@node Introduction
@chapter Introduction
Focus is a project which aims to produce a computing environment which allows
you to focus on the work you are doing. focus consists of the following
components.

@table @asis
@item consoler
Library for interacting with the user via keys and display.

@item fonter
Library for drawing fonts on consoler displays.

@item boxer
A box game.

@item filler
A sample program to fill a display with color.

@item green
A screen-like application window manager.

@item pdfer
A pdf viewer.

@item imager
An image viewer.

@item sdlcsr
A consoler server implemented on libSDL.

@item termer
A terminal emulator.
@end table

Each of these components is described in more detail in the following
sections.

@include boxer/boxer.texi

@bye
