\input texinfo
@setfilename focus.info
@include version.texi
@settitle Focus @value{VERSION} Manual

@copying
This is the Focus @value{VERSION} Manual.

Copyright @copyright{} 2014 Richard Uhler.
@end copying

@titlepage
@title Focus @value{VERSION}
@page
@insertcopying
@end titlepage

@contents

@ifnottex
@node Top
@top Focus Manual

@end ifnottex

@menu
* Introduction:: Introduction to the focus system.
* Boxer:: A Box Game
@end menu

@include intro.texi
@include boxer/boxer.texi

@bye
